### ISSUE TITLE
Can't run on Ubuntu

### ISSUE THREAD

**Issue by Radoslaw-K** [nachoparker/qemu-raspbian-network#1]
Hi,
First of all I'd like to thank you for putting this work out I've been looking to emulate raspberry pi with networking access for a while now. I'm very keen to see this project working but I've encountered errors when trying to run it.

**First of all:**

```
sudo apt-get install kvm qemu qemu-kvm-extras bridge-utils
```

Gives me:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'qemu-kvm' instead of 'kvm'
Package qemu-kvm-extras is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qemu-kvm-extras' has no installation candidate
```

**Secondly:**

Launching qemu:
```
sudo ./qemu-pi.sh 2017-01-11-raspbian-jessie-lite.img # correct to real name
```

Starts going through boot process but then quickly shuts down with this error:

```
no IP found for enp3s0
need to tun module
umount: /home/rados/qemu-raspbian-network/tmpmnt: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
pulseaudio: set_sink_input_volume() failed
pulseaudio: Reason: Invalid argument
pulseaudio: set_sink_input_mute() failed
pulseaudio: Reason: Invalid argument

```

**More info:**
I'm trying to run your project on Ubuntu 16.04.1 Xenial (4.4.0-59-generic).

**Comment by nachoparker** [comment]
sorry, I did not see the notification for this.

What is your interface name? if it is `eth0`, then you have to replace `enp3s0` for `eth0`

If that does not work, reopen and post here the output of `ip address`

**Comment by Iolaum** [comment]
I had the same problem with Ubuntu 17.10. I solved by replacing `IFACE=enp3s0` with `IFACE=wlp2s0` which I found from the outcome of `ip a`.

**Comment by nachoparker** [comment]
`wlp2s0` is a wifi interface, you should use whatever interface you are using for internet
