### ISSUE TITLE
Pulseaudio error in Ubuntu 17.10

### ISSUE THREAD

**Issue by Iolaum** [nachoparker/qemu-raspbian-network#10]
I tried qemu-raspbian-network in Ubuntu 17.10, since it has qemu 2.10 which should support raspberry pi 2 better.

However I run into this error:

```
$ sudo ./qemu-pi.sh 2017-09-07-raspbian-stretch-lite.img 
[sudo] password for nikolaos: 
need tun module
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
pulseaudio: pa_context_connect() failed
pulseaudio: Reason: Connection refused
pulseaudio: Failed to initialize PA contextaudio: Could not init `pa' audio driver
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
No protocol specified
Could not initialize SDL(No available video device) - exiting 
```

This doesn't appear to be an error of qemu-raspbian-network but an Ubuntu / Gnome3 related error. Couldn't get it fixed though.

**Comment by nachoparker** [comment]
```
need tun module
```

You need to install this kernel module. 

I am running in Arch version 2.11, so your version should be fine.

I don't get those other erros that you see.

**Comment by Iolaum** [comment]
Cool, thanks for the clarification.
